name: Build and Push Docker Image
on:
  push:
    branches:
      - main

permissions:
  contents: write    # Required for creating and pushing tags

jobs:
  create-tag-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: previoustag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0.0")
          echo "latest_tag=${latest_tag}" >> $GITHUB_OUTPUT

      - name: Generate version
        id: version
        run: |
          IFS='.' read -r major minor patch <<< "${{ steps.previoustag.outputs.latest_tag }}"
          new_patch=$((patch + 1))
          new_version="${major}.${minor}.${new_patch}"
          echo "version=${new_version}" >> $GITHUB_OUTPUT

      - name: Set up Git and Push Tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    needs: create-tag-release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            tinkeshwar/video-optimizer-ai:latest
            tinkeshwar/video-optimizer-ai:${{ needs.create-tag-release.outputs.version }}
          cache-from: type=registry,ref=tinkeshwar/video-optimizer-ai:latest
          cache-to: type=inline